SELECT * FROM club;

# K리그 1 클럽 데이터

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW() ,
`name` = '울산',
clubCode = 'Ulsan',
leagueId = 1,
fullname = '울산 현대',
location = '울산광역시',
homeGround = '울산 문수 축구경기장',
since = '1983',
coach = '김도훈',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
leagueId = 1,
clubCode = 'Jeonbuk',
`name` = '전북',
fullname = '전북 현대 모터스',
location = '전라북도',
homeGround = '전주 월드컵경기장',
since = '1994',
coach = '주제 모라이스',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '상주',
clubCode = 'Sangju',
leagueId = 1,
fullname = '상주 상무',
location = '경상북도 상주시',
homeGround = '상주 시민운동장',
since = '1984',
coach = '김태완',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '포항',
clubCode = 'Pohang',
leagueId = 1,
fullname = '포항 스틸러스',
location = '경상북도 포항시',
homeGround = '포항 스틸야드',
since = '1973',
coach = '김기동',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '대구',
clubCode = 'Daegu',
leagueId = 1,
fullname = '대구 FC',
location = '대구광역시',
homeGround = 'DGB 대구은행파크',
since = '2002',
coach = '이병근(대행)',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '강원',
clubCode = 'Gangwon',
leagueId = 1,
fullname = '강원 FC',
location = '강원도',
homeGround = '춘천 송암스포츠타운, 강릉 종합운동장',
since = '2008',
coach = '김병수',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '광주',
clubCode = 'Gwangju',
leagueId = 1,
fullname = '광주 FC',
location = '광주광역시',
homeGround = '광주 축구전용구장',
since = '2010',
coach = '박진섭',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '서울',
clubCode = 'Seoul',
leagueId = 1,
fullname = 'FC 서울',
location = '서울특별시',
homeGround = '서울 월드컵경기장',
since = '1983',
coach = '김호영(대행)',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '부산',
clubCode = 'Busan',
leagueId = 1,
fullname = '부산 아이파크',
location = '부산광역시',
homeGround = '구덕운동장',
since = '1979',
coach = '조덕제',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '성남',
clubCode = 'Seongnam',
leagueId = 1,
fullname = '성남 FC',
location = '경기도 성남시',
homeGround = '탄천 종합운동장',
since = '1989',
coach = '김남일',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '수원',
clubCode = 'Suwon',
leagueId = 1,
fullname = '수원 삼성 블루윙즈',
location = '경기도 수원시',
homeGround = '수원 월드컵경기장',
since = '1995',
coach = '주승진(대행)',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '인천',
clubCode = 'Incheon',
leagueId = 1,
fullname = '인천 유나이티드',
location = '인천광역시',
homeGround = '인천 축구전용구장',
since = '2003',
coach = '조성환',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

# K리그 2 데이터

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '제주',
clubCode = 'Jeju',
leagueId = 2,
fullname = '제주 유나이티드',
location = '제주특벌자치도 서귀포시',
homeGround = '제주 월드컵경기장',
since = '1982',
coach = '남기일',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '수원FC',
clubCode = 'SuwonFC',
leagueId = 2,
fullname = '수원 FC',
location = '경기도 수원시',
homeGround = '수원 종합운동장',
since = '2003',
coach = '김도균',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '대전',
clubCode = 'Daejeon',
leagueId = 2,
fullname = '대전 하나 시티즌',
location = '대전광역시',
homeGround = '대전 월드컵경기장',
since = '1997',
coach = '황선홍',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '경남',
clubCode = 'Gyeongnam',
leagueId = 2,
fullname = '경남 FC',
location = '경상남도',
homeGround = '창원 축구센터',
since = '2006',
coach = '설기현',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '서울E',
clubCode = 'SeoulE',
leagueId = 2,
fullname = '서울 이랜드 FC',
location = '서울특별시',
homeGround = '잠실 종합운동장',
since = '2014',
coach = '정정용',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '전남',
clubCode = 'Jeonnam',
leagueId = 2,
fullname = '전남 드래곤즈',
location = '전라남도',
homeGround = '광양 축구전용구장',
since = '1994',
coach = '전경준',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '부천',
clubCode = 'Bucheon',
leagueId = 2,
fullname = '부천 FC 1995',
location = '경기도 부천시',
homeGround = '부천 종합운동장',
since = '2007',
coach = '송선호',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '안양',
clubCode = 'Anyang',
leagueId = 2,
fullname = 'FC 안양',
location = '경기도 안양시',
homeGround = '안양 종합운동장',
since = '2013',
coach = '김형열',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '아산',
clubCode = 'Asan',
leagueId = 2,
fullname = '충남 아산 FC',
location = '충청남도 아산시',
homeGround = '이순신 종합운동장',
since = '2020',
coach = '박동혁',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '안산',
clubCode = 'Ansan',
leagueId = 2,
fullname = '안산 그리너스 FC',
location = '경기도 안산시',
homeGround = '안산 와~스타디움',
since = '2017',
coach = '김길식',
ranking = 0,
play = 0,
points = 0,
win = 0,
draw = 0,
defeat = 0,
goal = 0,
goalAgainst = 0;

# K3 리그 데이터

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '김해시청',
clubCode = 'Gimhae',
leagueId = 3,
fullname = '김해시청 축구단',
location = '경상남도 김해시',
homeGround = '김해운동장',
since = '2008',
coach = '윤성효',
ranking = 1,
play = 14,
points = 32,
win = 10,
draw = 2,
defeat = 2,
goal = 32,
goalAgainst = 14;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '강릉시청',
clubCode = 'Gangneung',
leagueId = 3,
fullname = '강릉시청 축구단',
location = '강원도 강릉시',
homeGround = '강릉 종합운동장',
since = '1999',
coach = '오세응',
ranking = 2,
play = 14,
points = 29,
win = 9,
draw = 2,
defeat = 3,
goal = 24,
goalAgainst = 12;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '경주한수원',
clubCode = 'GyeongjuKHNP',
leagueId = 3,
fullname = '경주 한국수력원자력',
location = '경상북도 경주시',
homeGround = '경주 시민운동장',
since = '1945',
coach = '서보원',
ranking = 3,
play = 14,
points = 28,
win = 8,
draw = 4,
defeat = 2,
goal = 27,
goalAgainst = 12;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '화성',
clubCode = 'Hwaseong',
leagueId = 3,
fullname = '화성 FC',
location = '경기도 화성시',
homeGround = '화성 종합경기타운',
since = '2013',
coach = '김학철',
ranking = 4,
play = 14,
points = 27,
win = 8,
draw = 3,
defeat = 3,
goal = 19,
goalAgainst = 14;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '부산교통공사',
clubCode = 'BusanTC',
leagueId = 3,
fullname = '부산교통공사 축구단',
location = '부산광역시',
homeGround = '구덕운동장',
since = '2006',
coach = '김귀화',
ranking = 5,
play = 14,
points = 26,
win = 7,
draw = 5,
defeat = 2,
goal = 26,
goalAgainst = 11;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '대전한국철도',
clubCode = 'DaejeonKorail',
leagueId = 3,
fullname = '대전 한국철도 축구단',
location = '대전광역시',
homeGround = '한밭 종합운동장',
since = '1943',
coach = '김승희',
ranking = 6,
play = 14,
points = 25,
win = 7,
draw = 4,
defeat = 3,
goal = 25,
goalAgainst = 11;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '목포시청',
clubCode = 'Mokpo',
leagueId = 3,
fullname = '목포시청 축구단',
location = '전라남도 목포시',
homeGround = '목포 국제축구센터',
since = '2009',
coach = '정현호',
ranking = 7,
play = 14,
points = 21,
win = 6,
draw = 3,
defeat = 5,
goal = 28,
goalAgainst = 18;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '김포시민',
clubCode = 'Gimpo',
leagueId = 3,
fullname = '김포시민 축구단',
location = '경기도 김포시',
homeGround = '김포 종합운동장',
since = '2013',
coach = '고정운',
ranking = 8,
play = 14,
points = 21,
win = 5,
draw = 6,
defeat = 3,
goal = 20,
goalAgainst = 13;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '천안시',
clubCode = 'Cheonan',
leagueId = 3,
fullname = '천안시 축구단',
location = '충청남도 천안시',
homeGround = '천안 종합운동장',
since = '2008',
coach = '김태영',
ranking = 9,
play = 14,
points = 20,
win = 5,
draw = 5,
defeat = 4,
goal = 19,
goalAgainst = 19;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '청주FC',
clubCode = 'Cheongju',
leagueId = 3,
fullname = '청주 FC',
location = '충청북도 청주시',
homeGround = '청주 종합운동장',
since = '2002',
coach = '서원상',
ranking = 10,
play = 14,
points = 20,
win = 5,
draw = 5,
defeat = 4,
goal = 12,
goalAgainst = 12;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '창원시청',
clubCode = 'Changwon',
leagueId = 3,
fullname = '창원시청 축구단',
location = '경상남도 창원시',
homeGround = '창원 종합운동장',
since = '2005',
coach = '최경돈',
ranking = 11,
play = 14,
points = 17,
win = 4,
draw = 5,
defeat = 5,
goal = 14,
goalAgainst = 20;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '평택시티즌',
clubCode = 'Pyeongtaek',
leagueId = 3,
fullname = '평택 시티즌 FC',
location = '경기도 평택시',
homeGround = '소사벌 레포츠타운',
since = '2017',
coach = '윤상철',
ranking = 12,
play = 14,
points = 9,
win = 2,
draw = 3,
defeat = 9,
goal = 11,
goalAgainst = 29;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '경주시민',
clubCode = 'GyeongjuCitizen',
leagueId = 3,
fullname = '경주시민 축구단',
location = '경상북도 경주시',
homeGround = '경주 시민운동장',
since = '2008',
coach = '손현준',
ranking = 13,
play = 14,
points = 8,
win = 1,
draw = 5,
defeat = 8,
goal = 7,
goalAgainst = 21;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '전주시민',
clubCode = ' Jeonju',
leagueId = 3,
fullname = '전주시민 축구단',
location = '전라북도 전주시',
homeGround = '전주 종합운동장',
since = '2007',
coach = '양영철',
ranking = 14,
play = 14,
points = 8,
win = 2,
draw = 2,
defeat = 10,
goal = 11,
goalAgainst = 26;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '양주시민',
clubCode = 'Yangju',
leagueId = 3,
fullname = '양주시민 축구단',
location = '경기도 양주시',
homeGround = '고덕 생활체육공원 축구장',
since = '2007',
coach = '김성재',
ranking = 15,
play = 14,
points = 8,
win = 2,
draw = 2,
defeat = 10,
goal = 9,
goalAgainst = 32;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '춘천시민',
clubCode = 'Chuncheon',
leagueId = 3,
fullname = '춘천시민 축구단',
location = '강원도 춘천시',
homeGround = '춘천 송암스포츠타운',
since = '2009',
coach = '김경범',
ranking = 16,
play = 14,
points = 7,
win = 1,
draw = 4,
defeat = 9,
goal = 12,
goalAgainst = 32;

# K4 리그 데이터

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '포천시민',
clubCode = 'Pocheon',
leagueId = 4,
fullname = '포천시민 축구단',
location = '경기도 포천시',
homeGround = '포천 종합운동장',
since = '2008',
coach = '조만근',
ranking = 1,
play = 15,
points = 30,
win = 9,
draw = 3,
defeat = 3,
goal = 41,
goalAgainst = 15;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '울산시민',
clubCode = 'UlsanCitizen',
leagueId = 4,
fullname = '울산시민 축구단',
location = '울산광역시',
homeGround = '울산 종합운동장',
since = '2018',
coach = '윤균상',
ranking = 2,
play = 14,
points = 29,
win = 9,
draw = 2,
defeat = 3,
goal = 30,
goalAgainst = 18;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '파주시민',
clubCode = 'Paju',
leagueId = 4,
fullname = '파주시민축구단',
location = '경기도 파주시',
homeGround = '파주스타디움',
since = '2012',
coach = '이은노',
ranking = 3,
play = 14,
points = 28,
win = 8,
draw = 4,
defeat = 2,
goal = 22,
goalAgainst = 14;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '인천남동구민',
clubCode = 'Namdong',
leagueId = 4,
fullname = '인천남동구민 축구단',
location = '인천광역시 남동구',
homeGround = '남동공단 근린공원 축구장',
since = '2020',
coach = '김정재',
ranking = 4,
play = 14,
points = 25,
win = 8,
draw = 1,
defeat = 5,
goal = 29,
goalAgainst = 17;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '양평FC',
clubCode = 'Yangpyeong',
leagueId = 4,
fullname = '양평 FC',
location = '경기도 양평군',
homeGround = '용문 생활체육공원 축구장',
since = '2015',
coach = '김창윤',
ranking = 5,
play = 14,
points = 23,
win = 7,
draw = 2,
defeat = 5,
goal = 18,
goalAgainst = 18;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '진주시민',
clubCode = 'Jinju',
leagueId = 4,
fullname = '진주시민 축구단',
location = '경상남도 진주시',
homeGround = '진주 종합경기장',
since = '2019',
coach = '최청일',
ranking = 6,
play = 13,
points = 22,
win = 6,
draw = 4,
defeat = 3,
goal = 25,
goalAgainst = 17;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '시흥시민',
clubCode = 'Siheung',
leagueId = 4,
fullname = '시흥시민 축구단',
location = '경기도 시흥시',
homeGround = '정왕스타디움',
since = '2015',
coach = '정선우',
ranking = 7,
play = 14,
points = 21,
win = 6,
draw = 3,
defeat = 5,
goal = 25,
goalAgainst = 20;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '여주시민',
clubCode = 'Yeoju',
leagueId = 4,
fullname = '여주시민 축구단',
location = '경기도 여주시',
homeGround = '여주 종합운동장',
since = '2017',
coach = '심봉섭',
ranking = 8,
play = 13,
points = 20,
win = 6,
draw = 2,
defeat = 5,
goal = 20,
goalAgainst = 20;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '충주시민',
clubCode = 'Chungju',
leagueId = 4,
fullname = '충주시민 축구단',
location = '충청북도 충주시',
homeGround = '충주 탄금대 축구장',
since = '2017',
coach = '공문배',
ranking = 9,
play = 13,
points = 15,
win = 4,
draw = 3,
defeat = 6,
goal = 15,
goalAgainst = 20;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '이천시민',
clubCode = 'Icheon',
leagueId = 4,
fullname = '이천시민축구단',
location = '경기도 이천시',
homeGround = '이천 종합운동장',
since = '2009',
coach = '이영기',
ranking = 10,
play = 14,
points = 14,
win = 3,
draw = 5,
defeat = 6,
goal = 17,
goalAgainst = 25;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '고양시민',
clubCode = 'Goyang',
leagueId = 4,
fullname = '고양시민 축구단',
location = '경기도 고양시',
homeGround = '별무리경기장',
since = '2008',
coach = '김영호',
ranking = 11,
play = 14,
points = 11,
win = 3,
draw = 2,
defeat = 9,
goal = 22,
goalAgainst = 40;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '서울중랑',
clubCode = 'Jungnang',
leagueId = 4,
fullname = '서울 중랑 축구단',
location = '서울특별시 중랑구',
homeGround = '중랑 구립잔디운동장',
since = '1982',
coach = '김상화',
ranking = 12,
play = 14,
points = 9,
win = 2,
draw = 3,
defeat = 9,
goal = 14,
goalAgainst = 38;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '서울노원',
clubCode = 'Nowon',
leagueId = 4,
fullname = '서울노원 유나이티드',
location = '서울특별시 노원구',
homeGround = '노원 마들스타디움',
since = '2007',
coach = '이정재',
ranking = 13,
play = 14,
points = 5,
win = 1,
draw = 2,
defeat = 11,
goal = 14,
goalAgainst = 30;

# WK 리그 데이터

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '인천현대제철',
clubCode = 'W_Incheon',
leagueId = 5,
fullname = '인천 현대제철 레드엔젤스',
location = '인천광역시',
homeGround = '남동아시아드 럭비경기장',
since = '1993',
coach = '정성천',
ranking = 1,
play = 11,
points = 31,
win = 10,
draw = 1,
defeat = 0,
goal = 31,
goalAgainst = 3;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '경주한수원',
clubCode = 'W_Gyeongju',
leagueId = 5,
fullname = '경주 한국수력원자력 여자축구단',
location = '경상북도 경주시',
homeGround = '경주축구공원 3구장',
since = '2016',
coach = '송주희',
ranking = 2,
play = 11,
points = 24,
win = 7,
draw = 3,
defeat = 1,
goal = 21,
goalAgainst = 8;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '수원도시공사',
clubCode = 'W_Suwon',
leagueId = 5,
fullname = '수원도시공사 여자축구단',
location = '경기도 수원시',
homeGround = '수원 종합운동장',
since = '2008',
coach = '박길영',
ranking = 3,
play = 11,
points = 18,
win = 6,
draw = 0,
defeat = 5,
goal = 15,
goalAgainst = 11;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '화천KSPO',
clubCode = 'W_Hwacheon',
leagueId = 5,
fullname = '화천 KSPO',
location = '강원도 화천군',
homeGround = '화천 공설운동장',
since = '2011',
coach = '강재순',
ranking = 4,
play = 11,
points = 15,
win = 4,
draw = 3,
defeat = 4,
goal = 14,
goalAgainst = 19;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '세종스포츠토토',
clubCode = 'W_Sejong',
leagueId = 5,
fullname = '세종 스포츠토토',
location = '세종특별자치시',
homeGround = '세종 중앙체육공원',
since = '2011',
coach = '이지은',
ranking = 5,
play = 11,
points = 14,
win = 4,
draw = 2,
defeat = 5,
goal = 14,
goalAgainst = 23;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '창녕WFC',
clubCode = 'W_Changnyeong',
leagueId = 5,
fullname = '창녕 WFC',
location = '경상남도 창녕군',
homeGround = '창녕군 스포츠파크 공설운동장',
since = '2018',
coach = '신상우',
ranking = 6,
play = 11,
points = 13,
win = 3,
draw = 4,
defeat = 4,
goal = 16,
goalAgainst = 20;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '서울시청',
clubCode = 'W_Seoul',
leagueId = 5,
fullname = '서울시청 여자축구단',
location = '서울특별시',
homeGround = '서울종합운동장 보조경기장, 효창운동장, 목동종합운동장',
since = '2004',
coach = '유영실',
ranking = 7,
play = 11,
points = 5,
win = 1,
draw = 2,
defeat = 8,
goal = 13,
goalAgainst = 26;

INSERT INTO club
SET regDate = NOW(),
updateDate = NOW(),
`name` = '보은상무',
clubCode = 'W_Boeun',
leagueId = 5,
fullname = '보은 상무 여자축구단',
location = '충청북도 보은군',
homeGround = '보은 공설운동장',
since = '2007',
coach = '이미연',
ranking = 11,
play = 11,
points = 4,
win = 1,
draw = 1,
defeat = 9,
goal = 11,
goalAgainst = 25;
